POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "user": "644a4d002d98b306413dd5f7"
}